---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-sample
  name: webapp-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-sample
  template:
    metadata:
      labels:
        app: webapp-sample
    spec:
      containers:
        - name: webapp-sample
          image: gcr.io/arctiq-mission-302500/webapp-sample@sha256:9d481ec2b6168579230f816016b3b09c91529120cf1497a2e163f164441b58c6
          ports:
            - containerPort: 8080
