---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: 34.95.49.110:443

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
type: Opaque
data:
  # Add auth token here
  ARGOCD_AUTH_TOKEN:
