---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: argocd-server.argocd:443

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
type: Opaque
data:
  # Add ArgoCD credentials
  ARGOCD_USERNAME:
  ARGOCD_PASSWORD: 
