---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-dev
spec:
  workspaces:
    - name: source
      description: The workspace containing the Webapp Code
  params:
    - name: image-name
      description: The name of the image to be deployed
    - name: image-digest
      description: The digest of the image to be deployed
  results:
    - name: dev-endpoint
  steps:
    - name: update-image
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      workingDir: $(workspaces.source.path)/config/base
      script: |
        sed -i 's#-\sdigest:\ssha256.*#- digest: $(params.image-digest)#' kustomization.yaml

    - name: commit-tag-push
      image: docker.io/alpine/git@sha256:8715680f27333935bb384a678256faf8e8832a5f2a0d4a00c9d481111c5a29c0 #tag: v2.26.2
      workingDir: $(workspaces.source.path)
      script: |
        # Commit image update
        git add config/base/kustomization.yaml
        git commit -m "[Pipeline]: Update image to $(params.image-name)@$(params.image-digest)"

    - name: appctl-prepare
      image: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:1e36678d6f42c8d9c00f6accbe86cb3b3b26d39e55cb648c9468fd139e6e87e0 #tag: 324.0.0
      workingDir: $(workspaces.source.path)
      script: |
        appctl prepare dev

    - name: appclt-apply
      image: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:1e36678d6f42c8d9c00f6accbe86cb3b3b26d39e55cb648c9468fd139e6e87e0 #tag: 324.0.0
      workingDir: $(workspaces.source.path)
      script: |
        appctl apply dev