---
apiVersion: v1
kind: Secret
metadata:
  name: gcr-credentials
  annotations:
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  # Hardcoded to '_json_key'
  username: _json_key
  # Create Password Field with: https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
  password: