---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-repo-reference
spec:
  workspaces:
    - name: source
      description: The workspace containing the Webapp Code
  params:
    - name: ref-filename
      description: The file containing the Repo Reference
  results:
    - name: repo-url
      description: The URL for the deployment repo
  steps:
    - name: get-repo
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      workingDir: $(workspaces.source.path)
      script: |
        repo=`cat $(params.ref-filename)`

        echo -n "${repo}" | tee $(results.repo-url.path)
