---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-deploy-repo
spec:
  workspaces:
    - name: source
      description: The workspace containing the Webapp Code
  results:
    - name: deploy-repo-url
      description: The URL for the deployment repo
  steps:
    - name: get-repo
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      workingDir: $(workspaces.source.path)
      script: |
        repo=`cat deployment-repo`

        echo -n "${repo}" | tee $(results.deploy-repo-url.path)
