---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-version
spec:
  workspaces:
    - name: source
      description: The workspace containing the Webapp Code
  results:
    - name: webapp-version
      description: The current versio of the Webapp being built
  steps:
    - name: get-version
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        version=`cat version`
        runtime=`date +%s`

        echo -n "${version}-${runtime}" | tee $(results.webapp-version.path)
