---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  # Input GitHub username and password
  username:
  password: