---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-webapp-sample
spec:
  serviceAccountName: pipeline-sa
  pipelineRef:
    name: webapp-sample-pipeline
  params:
    - name: git-url
      value: "https://github.com/alain-baxter/webapp-sample.git"
    - name: git-revision
      value: "main"
    - name: image-name
      value: "gcr.io/arctiq-mission-302500/webapp-sample"
  workspaces:
    - name: app-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: deploy-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    - name: test-space
      emptyDir: {}