---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-sa
secrets:
  - name: github-credentials
  - name: gcr-credentials

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webapp-sample-build-template
spec:
  params:
    - name: git-url
      description: The git repository url
    - name: git-revision
      description: The git revision
    - name: image-name
      description: The output image name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: webapp-sample-build-
      spec:
        serviceAccountName: trigger-sa
        pipelineRef:
          name: webapp-sample-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-name
            value: $(tt.params.image-name)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi