---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-image
spec:
  workspaces:
    - name: source
      description: The workspace containing the Deployment Code
  params:
    - name: image-name
      description: The name of the new image
    - name: image-digest
      description: The digest of the new image
    - name: deploy-branch
      description: The branch of the deployer to commit to
  steps:
    - name: kustomize
      image: gcr.io/arctiq-mission-302500/kustomize@sha256:1573629db353c0900e42da95dd8cc4444858368204cfe618dd27a97ce1bfba2c # Tag: v3.8.1
      workingDir: $(workspaces.source.path)/config/base
      script: |
        kustomize edit set image $(params.image-name)@$(params.image-digest)

    - name: push
      image: docker.io/alpine/git@sha256:8715680f27333935bb384a678256faf8e8832a5f2a0d4a00c9d481111c5a29c0 #tag: v2.26.2
      workingDir: $(workspaces.source.path)
      script: |
        # Set users Data
        git config --global user.email "pipeline@example.org"
        git config --global user.name "pipeline"

        # Commit image update
        git add config/base/kustomization.yaml
        git commit -m "[Pipeline]: Update image to $(params.image-name)@$(params.image-digest)"

        git push origin HEAD:$(params.deploy-branch)